version: "2.2"

services:
  app:
    build: .
    ports:
      - 80:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASSWORD=db_password
      - DB_HOST=db
    command: ["python", "main.py"]


  db:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name

    ports:
      - 5436:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

