version: "3.3"

services:
  app:
    image: ${IMAGE_TAG}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:5000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name

