version: "2.2"

services:
  app:
    image: ${IMAGE_TAG}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
    ports:
      - 5436:5432

